### ISSUE TITLE
Prefpane Problems

### ISSUE THREAD

**Issue by rafaelmaeuer** [mczachurski/wallpapper#33] opened 2019-05-08 16:58 UTC
This has been already handled in [#15](https://github.com/mczachurski/wallpapper/issues/15), as the preview is not showing the correct wallpaper. But I have another issue in the prefpane: The options for setting the wallpaper dynamic or static is overlaying with the options for light or dark mode - see Screenshot attached. How can this be fixed?
![Bildschirmfoto 2019-05-08 um 18 51 54](https://user-images.githubusercontent.com/6418459/57393369-3bf53d80-71c3-11e9-84ef-43fb303c9656.png)

**Comment by mczachurski** [comment] 2019-05-09 05:34
I have the same issue. This bug have to be fixed by Apple. Maybe you can report a bug directly to Apple.

**Comment by rafaelmaeuer** [comment] 2019-05-09 14:23
But when I create the same set of wallpapers with the dynaper app the problem disappears (except the watermark of course):
![Bildschirmfoto 2019-05-09 um 16 19 30](https://user-images.githubusercontent.com/6418459/57461095-af0bbc00-7276-11e9-8474-cf6a4d52c1d6.png)

**Comment by mczachurski** [comment] 2019-05-09 17:24
Ooooo. So I have to investigate this.

**Comment by thisispete** [comment] 2019-10-08 16:56
It looks like it has something to do with the image size preference, I'm getting overlaid: 
"Dynamic | Light (Still) | Dark (Still)" with "Fill Screen | Fit to Screen | Stretch to Fill Screen | Center | Tile" options. 
![Screen Shot 2019-10-08 at 9 54 32 AM](https://user-images.githubusercontent.com/677565/66416075-e6ab9b00-e9b1-11e9-803a-670364c0fe67.png)
![Screen Shot 2019-10-08 at 9 54 39 AM](https://user-images.githubusercontent.com/677565/66416077-e7443180-e9b1-11e9-8708-0d6291a39a6f.png)

**Comment by rafaelmaeuer** [comment] 2020-01-25 16:30
Anything new here? The problem still persists in Catalina...
![Bildschirmfoto 2020-01-25 um 17 20 24](https://user-images.githubusercontent.com/6418459/73124162-69c02380-3f98-11ea-8e36-8b1ab5934b7a.png)

**Comment by zerotao** [comment] 2020-02-09 15:56
Strange, I had the same issue and then placed the .heic in `/Library/Desktop Pictures` and it fixed it.

**Comment by mczachurski** [comment] 2021-01-13 20:25
The issue is on Apple side. There is a few workarounds:
 - place image in `/Library/Desktop Pictures` folder
 - create wallpaper without `isForDark` and `isForLight` (Appearance) flags

**Closed by mczachurski** 2021-01-13 20:25 UTC
