### ISSUE TITLE
Is the limit still 16 images?

### ISSUE THREAD

**Issue by buschco** [mczachurski/wallpapper#12] opened 2018-09-26 09:44 UTC
Did anyone tried more?

**Comment by JohnSlaughter** [comment] 2018-09-27 14:48
I've made a test with a new image every 15 minutes, so it is possible, but Apple only reads them about every 1.5 hours so it's not beneficial to do so..

**Comment by iAlborz** [comment] 2018-09-27 18:20
I made one with 24 hours. but it won't go past 16. it goes 16 then 1 when I change the time. Any help would be appreciated.

**Comment by ctw-braun** [comment] 2018-09-28 02:53
Hi Guys,
I have maybe the same problem with the timezone altitude/ azimuth

I'm from switzerland (UTC+2) and i created a wallpaper from Livigno, Italy (same zone). So far so good.

Now i added to the json file the altitude/azimuth from the location of the picture based on 1. Aug 2018. I set my first picture to dawn, 2. to sunrise, … 8. to culmination, … 11. to sunset, 12. dusk …

With these settings i get the best effect :) on my main screen did i used the original Mojave dynamic and on the secondary screen my own wallpaper.  The main screen displayed mojave by night and the second screen displays my picture by daylight!! So one screen is thinking "oh it's day" and the other "oh it's night" After a lot of tries, i got the best solution and on both screens similar pictures with the timezone from "mojave desert" UTC-7 at 21. jun 2018 (it's the longest day this year)

I setup the date and time in the setting to this date (2018/06/21) and to sunrise time (5:28am) and both screens display the sunrise picture. In my opinion works it only correct with these settings, because i think this tool isn't ready for our own wallpapers :) We can see the dropdown didn't work correct, if u put the wallpaper in your pictures folder. BUT if u put it into the /library/Desktop Pictures folder it works.

I attach for you my json file, hopefully it helps you.

Have a nice day


[livigno.txt](https://github.com/mczachurski/wallpapper/files/2426583/livigno.txt)

**Comment by red-green** [comment] 2018-12-20 21:38
I made myself a few desktops with 102 images each ([link here](https://drive.google.com/open?id=1YeUHTcD6KGBz2ld0feZ7uV1c6ZjpFa_f) if you want to test them out). They seem, from my initial test at least, to go through every image sequentially. I had to generate the coordinates based on my current location and season to get them to sync correctly, but so far I have not seen any images skip for a few hours so far. This is with the latest Mojave (10.14.2).

**Comment by sbliven** [comment] 2019-02-06 15:59
I did some tests!

*Hypothesis:* Apple periodically calculates the correct elevation/azimuth from the time and location. It then searches the heic for the image closest to that position in the sky.

*Test:* Generate a heic with an image every 10 degrees of elevation/azimuth (180/10*360/10=648 images). Script: https://gist.github.com/sbliven/7287fa4f37d8abdcfe757a3813f8e6cd

*Results:*
<img width="392" alt="Graphs elevation and azimuth by time of day" src="https://user-images.githubusercontent.com/595872/52352572-2427e500-2a2d-11e9-8f75-18042cff181e.png">
The blue and orange lines (at 15 min increments) show the calculated elevation and azimuth for my location (Zurich) and for the equator (0N 0E) for today's date (Feb 6, 2016). I then set the time on my computer every hour and recorded which image was displayed. I first did this with location services off (grey points) and then with location on (yellow line).

- Sometimes the image shown was inconsistent. To get reproducible results I had to switch to the Mojave screen save and back occasionally after switching the time.
- Using such a large heic file worked, but loading the Desktop preference pane becomes very slow (10s of seconds). Sometimes updating the image after changing the time was slow too.
- Images are sorted internally first by elevation and then by azimuth.

*Conclusions:*  
- If location services are turned off, apple assumes an equatorial position
- The elevation is generally calculated correctly, but the azimuth jumps around a lot. I'm guessing this is due to some heuristic for finding the best image for a particular sun position. Changing the image order might have an impact, but I haven't tested it.
- It might be feasible to show different images for different seasons (at least at noon/midnight)
- Still not fully predictable what image will be shown for a particular sun position.

**Comment by nzamosenchuk** [comment] 2020-03-31 08:29
Does anyone have the sun positions json exactly matching Apple's Mojave wallpaper with 16 images?
Would appreciate a lot! Thank you.

**Comment by ephilippo** [comment] 2021-01-18 09:22
> Does anyone have the sun positions json exactly matching Apple's Mojave wallpaper with 16  #images?

Yes, see [this reply](https://github.com/mczachurski/wallpapper/issues/31#issuecomment-462237264) to a previous issue.

**Comment by mczachurski** [comment] 2021-01-21 16:04
It seems that there is no limit of 16 images in macOS now. For sure you can use wallpapper for creating HEIC file with more (or less) than 16 images. I'm closing the issue.

**Closed by mczachurski** 2021-01-21 16:04 UTC
Labels: discussion
